

#define EMBER_XNCP_TEST_HARNESS_VERSION_NUMBER 0x7822  // arbitrary number

#define EMBER_XNCP_TEST_HARNESS_COMMAND_RESET_APS_FRAME_COUNTER   0x01
#define EMBER_XNCP_TEST_HARNESS_COMMAND_ADVANCE_APS_FRAME_COUNTER 0x02
